# action.yml
# name: 'Hello World'
# description: 'Greet someone and record the time'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
# runs:
#   using: 'docker'
#   image: 'Dockerfile'
#   args:
#     - ${{ inputs.who-to-greet }}

name: 'Set env variable for host'
description: 'set env variable for host'
inputs:
  dev_env_host_ip:
    description: 'Host IP for the dev branch'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    - name: dev_env_host_ip
      value: ${{ inputs.dev_env_host_ip }}
  args:
    - ${{ inputs.dev_env_host_ip }}

  

